server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    prefix: classpath:/
    suffix: .html
    view-names: templates/*  # Thymeleaf에 연결될 viewname 범위 설정